# -*- coding: utf-8 -*-
"""q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jaMbs2_Pge-_a3Zb-CQuMwxGY9jLAmd
"""

import copy
from collections import defaultdict

# ====================== HELPER FUNCTIONS ======================

def read_sudoku(filename):
    """Read Sudoku board from text file (9 lines, 9 digits each)."""
    with open(filename, 'r') as f:
        board = [[int(ch) for ch in line.strip()] for line in f.readlines() if line.strip()]
    return board

def print_board(board):
    """Pretty print the Sudoku board."""
    for i, row in enumerate(board):
        if i % 3 == 0 and i != 0:
            print("-" * 21)
        print(" ".join(str(cell) if cell != 0 else "." for cell in row))

# ====================== CSP REPRESENTATION ======================

def get_variables():
    """All 81 cell positions as variables: (row, col) tuples."""
    return [(r, c) for r in range(9) for c in range(9)]

def get_domains(board):
    """Initial domains: fixed cells have singleton domain, empty cells have {1..9}."""
    domains = {}
    for r in range(9):
        for c in range(9):
            if board[r][c] != 0:
                domains[(r, c)] = {board[r][c]}
            else:
                domains[(r, c)] = set(range(1, 10))
    return domains

def get_neighbors(var):
    """Return all variables that share a row, column, or 3x3 box with var."""
    r, c = var
    neighbors = set()

    # Same row
    for i in range(9):
        if i != c:
            neighbors.add((r, i))
    # Same column
    for i in range(9):
        if i != r:
            neighbors.add((i, c))
    # Same 3x3 box
    box_r, box_c = r // 3 * 3, c // 3 * 3
    for i in range(box_r, box_r + 3):
        for j in range(box_c, box_c + 3):
            if (i, j) != (r, c):
                neighbors.add((i, j))
    return neighbors

# ====================== AC-3 ALGORITHM ======================

def ac3(domains, queue=None):
    """Arc Consistency Algorithm #3. Returns False if inconsistency found."""
    if queue is None:
        # Initialize queue with all arcs (X, Y) where Y is neighbor of X
        queue = [(X, Y) for X in get_variables() for Y in get_neighbors(X)]

    while queue:
        X, Y = queue.pop(0)
        if revise(domains, X, Y):
            if not domains[X]:          # Domain wipeout → no solution
                return False
            # Add all arcs (Z, X) where Z is neighbor of X (except Y)
            for Z in get_neighbors(X):
                if Z != Y:
                    queue.append((Z, X))
    return True

def revise(domains, X, Y):
    """Remove values from X's domain that have no support in Y's domain."""
    revised = False
    to_remove = []
    for x in domains[X]:
        # If no value in Y's domain is different from x (i.e., all equal to x)
        if all(x == y for y in domains[Y]):
            to_remove.append(x)
            revised = True
    for val in to_remove:
        domains[X].remove(val)
    return revised

# ====================== BACKTRACKING SEARCH ======================

backtrack_calls = 0
backtrack_failures = 0

def select_unassigned_variable(domains, assignment):
    """MRV heuristic: variable with smallest domain (not yet assigned)."""
    unassigned = [v for v in domains if v not in assignment]
    return min(unassigned, key=lambda v: len(domains[v]))

def is_consistent(var, value, assignment, domains):
    """Check if value is consistent with current assignment (row/col/box)."""
    r, c = var
    for (ar, ac), aval in assignment.items():
        if aval == value:
            if ar == r or ac == c or (ar//3 == r//3 and ac//3 == c//3):
                return False
    return True

def forward_check(domains, var, value, assignment):
    """Remove value from neighbors' domains (simple forward checking)."""
    for neighbor in get_neighbors(var):
        if neighbor not in assignment and value in domains[neighbor]:
            domains[neighbor].remove(value)
            if not domains[neighbor]:
                return False
    return True

def restore_domains(domains, var, value, saved_domains):
    """Restore domains after forward checking (by copying back)."""
    for neighbor in get_neighbors(var):
        if neighbor not in assignment:   # only unassigned
            domains[neighbor] = saved_domains[neighbor].copy()

def backtrack(assignment, domains, original_board):
    """Recursive backtracking search with AC-3 + forward checking."""
    global backtrack_calls, backtrack_failures
    backtrack_calls += 1

    if len(assignment) == 81:           # All variables assigned
        return True

    var = select_unassigned_variable(domains, assignment)

    # Try values in order (could be LCV heuristic, but keep simple)
    for value in sorted(domains[var]):
        if is_consistent(var, value, assignment, domains):
            assignment[var] = value

            # Save current domains for restoration
            saved = {v: domains[v].copy() for v in domains if v not in assignment}

            if forward_check(domains, var, value, assignment):
                # Optional: run AC-3 after assignment (more powerful but slower)
                # if ac3(domains, [(n, var) for n in get_neighbors(var)]):
                if backtrack(assignment, domains, original_board):
                    return True

            # Backtrack
            del assignment[var]
            # Restore domains
            for v in saved:
                domains[v] = saved[v]

    backtrack_failures += 1
    return False

# ====================== MAIN SOLVER ======================

def solve_sudoku(board):
    """Solve one Sudoku board and return solution + stats."""
    global backtrack_calls, backtrack_failures
    backtrack_calls = 0
    backtrack_failures = 0

    domains = get_domains(board)
    assignment = {(r, c): board[r][c] for r in range(9) for c in range(9) if board[r][c] != 0}

    # Initial AC-3 for constraint propagation
    if not ac3(domains):
        return None, 0, 0

    # Solve with backtracking
    if backtrack(assignment, domains, board):
        # Build solution board
        solution = [row[:] for row in board]
        for (r, c), val in assignment.items():
            solution[r][c] = val
        return solution, backtrack_calls, backtrack_failures
    else:
        return None, backtrack_calls, backtrack_failures

# ====================== RUN ON ALL FILES ======================

files = ["easy.txt", "medium.txt", "hard.txt", "veryhard.txt"]

for filename in files:
    print(f"\n{'='*60}")
    print(f"Solving {filename}...")
    board = read_sudoku(filename)

    print("Original board:")
    print_board(board)

    solution, calls, failures = solve_sudoku(board)

    if solution:
        print("\nSolution:")
        print_board(solution)
        print(f"\nBacktrack calls: {calls}")
        print(f"Backtrack failures: {failures}")

        if calls == 1 and failures == 0:
            print("→ Solved with pure AC-3 (no search needed)")
        elif failures == 0:
            print("→ Very little backtracking (good propagation)")
        elif failures < calls // 10:
            print("→ Moderate backtracking")
        else:
            print("→ Heavy backtracking required")
    else:
        print("No solution found!")